apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dnlf8bfs6-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/dnlf8bfs6-java-springboot-gitops